# Generated by Django 5.2.6 on 2025-09-11 17:55

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('library', '0002_alter_book_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('due_date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='Дата возврата')),
                ('book_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='library.bookitem', verbose_name='Экземпляр книги')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.member', verbose_name='Читатель')),
            ],
            options={
                'verbose_name': 'Выдача книги',
                'verbose_name_plural': 'Выдачи книг',
            },
        ),
    ]
