# Generated by Django 5.2.6 on 2025-09-23 13:39

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_librarian_options_alter_member_options_and_more'),
        ('borrowing', '0001_initial'),
        ('library', '0003_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowedbook',
            options={'ordering': ['due_date', 'borrowed_date'], 'verbose_name': 'Выдача книги', 'verbose_name_plural': 'Выдачи книг'},
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='book_item',
            field=models.OneToOneField(help_text='Конкретный экземпляр книги, который выдается читателю', on_delete=django.db.models.deletion.CASCADE, related_name='borrowedbook', to='library.bookitem', verbose_name='Экземпляр книги'),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='borrowed_date',
            field=models.DateField(auto_now_add=True, help_text='Дата, когда книга была выдана читателю', verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='borrower',
            field=models.ForeignKey(help_text='Читатель, который взял книгу', on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_books', to='accounts.member', verbose_name='Читатель'),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='due_date',
            field=models.DateField(help_text='Планируемая дата возврата книги', validators=[django.core.validators.MinValueValidator(datetime.date.today)], verbose_name='Дата возврата'),
        ),
        migrations.AddIndex(
            model_name='borrowedbook',
            index=models.Index(fields=['due_date'], name='borrowing_b_due_dat_ce6b28_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowedbook',
            index=models.Index(fields=['borrowed_date'], name='borrowing_b_borrowe_359c00_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowedbook',
            index=models.Index(fields=['borrower'], name='borrowing_b_borrowe_cecda9_idx'),
        ),
        migrations.AddConstraint(
            model_name='borrowedbook',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('borrowed_date'))), name='due_date_after_borrowed_date'),
        ),
    ]
