# Generated by Django 5.2.6 on 2025-09-23 13:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarian',
            options={'verbose_name': 'Библиотекарь', 'verbose_name_plural': 'Библиотекари'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Читатель', 'verbose_name_plural': 'Читатели'},
        ),
        migrations.AlterField(
            model_name='librarian',
            name='staff_code',
            field=models.CharField(help_text='Уникальный код сотрудника (например: LIB00001)', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Код должен быть в формате: 3 заглавные буквы + 5 цифр', regex='^[A-Z]{3}\\d{5}$')], verbose_name='Код сотрудника'),
        ),
        migrations.AlterField(
            model_name='librarian',
            name='user',
            field=models.OneToOneField(help_text='Связанный пользователь системы', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_code',
            field=models.CharField(help_text='Уникальный код читательского билета (например: MEM00001)', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Код должен быть в формате: 3 заглавные буквы + 5 цифр', regex='^[A-Z]{3}\\d{5}$')], verbose_name='Код читателя'),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(help_text='Связанный пользователь системы', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='librarian',
            index=models.Index(fields=['staff_code'], name='accounts_li_staff_c_7b7f05_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['membership_code'], name='accounts_me_members_b879c2_idx'),
        ),
    ]
